### ISSUE TITLE
LIBKML unavailable

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/mapme-docker#12]
I'm having trouble reading kml/kmz files on the dsap, it seems like the `LIBKML` driver is unavailable.
The issues are the same as described here: https://github.com/r-spatial/sf/issues/499.

Maybe we can add the driver in a future release.

**Comment by goergen95** [comment]
please find release [1.4.0](https://github.com/mapme-initiative/mapme-docker/releases/tag/1.4.0)
