### ISSUE TITLE
Bump to GDAL 3.9.0

### ISSUE THREAD

**Issue by goergen95** [mapme-initiative/mapme-docker#3]
[GDAL 3.9.0](https://github.com/OSGeo/gdal/releases/tag/v3.9.0) was released. The images should be updated accordingly. Still thinking about versioning the tags of the images here. We could increase major version in case we update/upgrade dependencies, thus this would result in `mapme-spatial:2.0.0` in this case. Or we only increase the major component in case we change how the image is built, thus updating GDAL here would result in `mapme-spatial:1.2.0`. @karpfen, any thoughts?

**Comment by karpfen** [comment]
Hi @goergen95, some thoughts, but absolutely no strong opinion.

I'm tending toward `mapme-spatial:1.2.0`, since it's "just" a dependency version bump.
Thinking about this, maybe it *could* be useful if the build version reflects the `mapme.biodiversity` version that is inside, so e.g.  `mapme-spatial:0.6.0.x`. But I don't know if that is good practice, a good idea or actually helpful for anyone.

**Comment by goergen95** [comment]
Thanks for your comment! I also agree that a "simple" bump of version is somewhat over-to-top for an increase in the major version number. 

The idea of reflecting the version of `mapme.biodiversity` does not make totally sense to me. The main purpose of these images (to me) is to get specific versions of GDAL/PROJ/GEOS to work with either the CRAN or GitHub version of the R package. I think what your are suggesting goes into the direction to build images for each release of `mapme.biodiversity`, which I currently do not see a need for. You can always install specific versions e.g. via `remotes::install_version("mapme.biodiversity", version = "0.5")`. The hard part is to control the version of GDAL that might be needed in case you rely on specific functionality, e.g. for cloud provider drivers, only available in recent versions.

**Comment by karpfen** [comment]
Yes, good point. In that case, I'd say let's just go with `mapme-spatial:1.2.0`.
